export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const CREATE_CITY_REQUEST = 'CREATE_CITY_REQUEST';
export const CREATE_CITY_SUCCESS = 'CREATE_CITY_SUCCESS';
export const CREATE_CITY_ERROR= 'CREATE_CITY_ERROR';

export const GET_CITYS_REQUEST = 'GET_CITYS_REQUEST';
export const GET_CITYS_SUCCESS = 'GET_CITYS_SUCCESS';
export const GET_CITYS_ERROR = 'GET_CITYS_ERROR';

export const GET_CITY_BY_ID_REQUEST = 'GET_CITY_BY_ID_REQUEST';
export const GET_CITY_BY_ID_SUCCESS = 'GET_CITY_BY_ID_SUCCESS';
export const GET_CITY_BY_ID_ERROR = 'GET_CITY_BY_ID_ERROR';

export const UPDATE_CITY_REQUEST = 'UPDATE_CITY_REQUEST';
export const UPDATE_CITY_SUCCESS = 'UPDATE_CITY_SUCCESS';
export const UPDATE_CITY_ERROR = 'UPDATE_CITY_ERROR';

export const DELETE_CITY_REQUEST = 'DELETE_CITY_REQUEST';
export const DELETE_CITY_SUCCESS = 'DELETE_CITY_SUCCESS';
export const DELETE_CITY_ERROR = 'DELETE_CITY_ERROR';


export const CREATE_GENRE_REQUEST = 'CREATE_GENRE_REQUEST';
export const CREATE_GENRE_SUCCESS = 'CREATE_GENRE_SUCCESS';
export const CREATE_GENRE_ERROR= 'CREATE_GENRE_ERROR';

export const GET_GENRES_REQUEST = 'GET_GENRES_REQUEST';
export const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS';
export const GET_GENRES_ERROR = 'GET_GENRES_ERROR';

export const GET_GENRE_BY_ID_REQUEST = 'GET_GENRE_BY_ID_REQUEST';
export const GET_GENRE_BY_ID_SUCCESS = 'GET_GENRE_BY_ID_SUCCESS';
export const GET_GENRE_BY_ID_ERROR = 'GET_GENRE_BY_ID_ERROR';

export const UPDATE_GENRE_REQUEST = 'UPDATE_GENRE_REQUEST';
export const UPDATE_GENRE_SUCCESS = 'UPDATE_GENRE_SUCCESS';
export const UPDATE_GENRE_ERROR = 'UPDATE_GENRE_ERROR';

export const DELETE_GENRE_REQUEST = 'DELETE_GENRE_REQUEST';
export const DELETE_GENRE_SUCCESS = 'DELETE_GENRE_SUCCESS';
export const DELETE_GENRE_ERROR = 'DELETE_GENRE_ERROR';

export const CREATE_BANNER_REQUEST = 'CREATE_BANNER_REQUEST';
export const CREATE_BANNER_SUCCESS = 'CREATE_BANNER_SUCCESS';
export const CREATE_BANNER_ERROR= 'CREATE_BANNER_ERROR';

export const GET_BANNERS_REQUEST = 'GET_BANNERS_REQUEST';
export const GET_BANNERS_SUCCESS = 'GET_BANNERS_SUCCESS';
export const GET_BANNERS_ERROR = 'GET_BANNERS_ERROR';

export const GET_BANNER_BY_ID_REQUEST = 'GET_BANNER_BY_ID_REQUEST';
export const GET_BANNER_BY_ID_SUCCESS = 'GET_BANNER_BY_ID_SUCCESS';
export const GET_BANNER_BY_ID_ERROR = 'GET_BANNER_BY_ID_ERROR';

export const UPDATE_BANNER_REQUEST = 'UPDATE_BANNER_REQUEST';
export const UPDATE_BANNER_SUCCESS = 'UPDATE_BANNER_SUCCESS';
export const UPDATE_BANNER_ERROR = 'UPDATE_BANNER_ERROR';

export const DELETE_BANNER_REQUEST = 'DELETE_BANNER_REQUEST';
export const DELETE_BANNER_SUCCESS = 'DELETE_BANNER_SUCCESS';
export const DELETE_BANNER_ERROR = 'DELETE_BANNER_ERROR';