export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const CREATE_CITY_REQUEST = 'CREATE_CITY_REQUEST';
export const CREATE_CITY_SUCCESS = 'CREATE_CITY_SUCCESS';
export const CREATE_CITY_ERROR= 'CREATE_CITY_ERROR';

export const GET_CITYS_REQUEST = 'GET_CITYS_REQUEST';
export const GET_CITYS_SUCCESS = 'GET_CITYS_SUCCESS';
export const GET_CITYS_ERROR = 'GET_CITYS_ERROR';

export const GET_CITY_BY_ID_REQUEST = 'GET_CITY_BY_ID_REQUEST';
export const GET_CITY_BY_ID_SUCCESS = 'GET_CITY_BY_ID_SUCCESS';
export const GET_CITY_BY_ID_ERROR = 'GET_CITY_BY_ID_ERROR';

export const UPDATE_CITY_REQUEST = 'UPDATE_CITY_REQUEST';
export const UPDATE_CITY_SUCCESS = 'UPDATE_CITY_SUCCESS';
export const UPDATE_CITY_ERROR = 'UPDATE_CITY_ERROR';

export const DELETE_CITY_REQUEST = 'DELETE_CITY_REQUEST';
export const DELETE_CITY_SUCCESS = 'DELETE_CITY_SUCCESS';
export const DELETE_CITY_ERROR = 'DELETE_CITY_ERROR';